# Generated by Django 4.0 on 2021-12-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField()),
                ('description', models.TextField()),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
            ],
        ),
    ]
