# Generated by Django 4.0 on 2022-01-26 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uservote',
            name='vote',
        ),
        migrations.AddField(
            model_name='uservote',
            name='user_id',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uservote',
            name='vote_id',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='users',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
