# Generated by Django 4.0 on 2022-01-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='answer1',
            new_name='answers',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='answer2',
        ),
    ]
